### ISSUE TITLE
Protect access with code/credentials

### ISSUE THREAD

**Issue by nuovodna** [zephyros-dev/docker-koreader#25]
Hi, i'd like to expose the koreader installation to the web. 
Can i protect the access with a code or something similar to prevent access from anyone?
Thanks

**Comment by zephyros-dev** [comment]
If you are using a reverse-proxy like nginx or caddy (which you really should if you are exposing it to the internet), I suggest using their respective http basic-auth configuration for the endpoint. You can lookup on how to do this in their documentation, for example with caddy: https://caddyserver.com/docs/caddyfile/directives/basic_auth

Otherwise there's also basic-auth options by setting the environment variables for the container: https://github.com/linuxserver/docker-baseimage-kasmvnc

**Comment by nuovodna** [comment]
made it with caddy, thank you!
